import type { Product, Category } from "./types";

// Helper to build local image path (served from Next.js public folder)
function img(n: number): string {
  return `/images/img${n}.jpeg`;
}

// All available image numbers (img37 and img43 don't exist)
const IMAGE_NUMBERS = [
  1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
  21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 38, 39,
  40, 41, 42, 44,
];

// Full pool of all backend images
export const IMAGE_POOL = IMAGE_NUMBERS.map((n) => img(n));

// Video pool (local + Cloudinary)
export const VIDEO_POOL = [
  "/images/video1.mp4",
  "/images/video2.mp4",
  "/images/video3.mp4",
  "/images/video4.mp4",
  "https://res.cloudinary.com/dfixnhqn0/video/upload/q_auto/f_auto/v1775306360/P14SJEsZQjk5AQRpYw___8_rp3zeo.mp4",
];

// Hero fallback image
export const HERO_FALLBACK = "/images/hero-2.webp";

// Shuffle utility (Fisher-Yates)
function shuffle<T>(arr: T[]): T[] {
  const s = [...arr];
  for (let i = s.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [s[i], s[j]] = [s[j], s[i]];
  }
  return s;
}

// Get N random unique images from the pool
export function getRandomImages(count: number): string[] {
  return shuffle(IMAGE_POOL).slice(0, count);
}

// Get a single random image
export function getRandomImage(): string {
  return IMAGE_POOL[Math.floor(Math.random() * IMAGE_POOL.length)];
}

// Get a random video URL
export function getRandomVideo(): string {
  return VIDEO_POOL[Math.floor(Math.random() * VIDEO_POOL.length)];
}

export const categories: Category[] = [
  {
    id: "1",
    name: "Premium Biscuits",
    slug: "premium-biscuits",
    image: img(1),
    description: "Finest quality biscuits from top international brands",
    productCount: 48,
  },
  {
    id: "2",
    name: "Chocolate Candies",
    slug: "chocolate-candies",
    image: img(3),
    description: "Rich, smooth chocolate candies for every occasion",
    productCount: 36,
  },
  {
    id: "3",
    name: "Hard Candies",
    slug: "hard-candies",
    image: img(5),
    description: "Classic hard candies in vibrant flavors",
    productCount: 28,
  },
  {
    id: "4",
    name: "Gummy & Jellies",
    slug: "gummy-jellies",
    image: img(7),
    description: "Fun chewy gummies and jelly treats",
    productCount: 32,
  },
  {
    id: "5",
    name: "Cream Wafers",
    slug: "cream-wafers",
    image: img(9),
    description: "Crispy wafers with creamy fillings",
    productCount: 22,
  },
  {
    id: "6",
    name: "Cookies & Crackers",
    slug: "cookies-crackers",
    image: img(11),
    description: "Assorted cookies and savory crackers",
    productCount: 40,
  },
];

export const products: Product[] = [
  {
    id: "1",
    name: "Royal Danish Butter Cookies",
    slug: "royal-danish-butter-cookies",
    description: "Authentic Danish butter cookies made with premium ingredients. Each tin contains an assortment of 7 unique cookie varieties.",
    price: 42.0,
    comparePrice: 48.0,
    images: [img(1), img(2)],
    category: "Premium Biscuits",
    brand: "Royal Danish",
    moq: 24,
    stock: 480,
    unit: "tins",
    ingredients: "Wheat flour, butter (26%), sugar, coconut, eggs, salt, vanilla.",
    packaging: "454g tin. Master carton: 12 tins per case.",
    deliveryInfo: "Standard delivery: 3-5 business days. Express: 1-2 business days.",
    featured: true,
  },
  {
    id: "2",
    name: "Belgian Dark Chocolate Truffles",
    slug: "belgian-dark-chocolate-truffles",
    description: "Luxurious dark chocolate truffles crafted with finest Belgian cocoa. Perfect for gifting and retail display.",
    price: 68.0,
    comparePrice: 78.0,
    images: [img(3), img(4)],
    category: "Chocolate Candies",
    brand: "Belcolade",
    moq: 12,
    stock: 240,
    unit: "boxes",
    ingredients: "Cocoa mass, sugar, cocoa butter, cream powder, vanilla extract.",
    packaging: "250g box. Master carton: 24 boxes per case.",
    deliveryInfo: "Temperature-controlled delivery. Standard: 3-5 business days.",
    featured: true,
  },
  {
    id: "3",
    name: "Japanese Matcha KitKat",
    slug: "japanese-matcha-kitkat",
    description: "Authentic Japanese Matcha flavored KitKat bars. A bestseller with exotic appeal for specialty retail stores.",
    price: 55.0,
    images: [img(5), img(6)],
    category: "Chocolate Candies",
    brand: "Nestle Japan",
    moq: 36,
    stock: 600,
    unit: "packs",
    ingredients: "Sugar, wheat flour, matcha green tea powder, cocoa butter, whole milk powder.",
    packaging: "12-piece pack. Master carton: 24 packs per case.",
    deliveryInfo: "Import item. Standard delivery: 5-7 business days.",
    featured: true,
  },
  {
    id: "4",
    name: "Haribo Gold Bears Mega Pack",
    slug: "haribo-gold-bears-mega",
    description: "The world's favourite gummy bears in bulk wholesale packs. Six fruity flavors loved by all ages.",
    price: 38.0,
    images: [img(7), img(8)],
    category: "Gummy & Jellies",
    brand: "Haribo",
    moq: 48,
    stock: 960,
    unit: "bags",
    ingredients: "Glucose syrup, sugar, gelatin, fruit juice concentrates, citric acid.",
    packaging: "500g bag. Master carton: 12 bags per case.",
    deliveryInfo: "Standard delivery: 3-5 business days.",
    featured: true,
  },
  {
    id: "5",
    name: "Lotus Biscoff Original",
    slug: "lotus-biscoff-original",
    description: "The iconic caramelised biscuit. Perfect for coffee accompaniment and retail. Individually wrapped.",
    price: 34.0,
    comparePrice: 39.0,
    images: [img(9), img(10)],
    category: "Premium Biscuits",
    brand: "Lotus",
    moq: 30,
    stock: 750,
    unit: "packs",
    ingredients: "Wheat flour, sugar, vegetable oils, candy sugar syrup, soy flour, cinnamon.",
    packaging: "250g pack (32 biscuits). Master carton: 10 packs per case.",
    deliveryInfo: "Standard delivery: 3-5 business days.",
    featured: true,
  },
  {
    id: "6",
    name: "Werther's Original Caramels",
    slug: "werthers-original-caramels",
    description: "Classic creamy caramel candies. An timeless favourite with premium positioning for retail.",
    price: 29.0,
    images: [img(11), img(12)],
    category: "Hard Candies",
    brand: "Werther's",
    moq: 24,
    stock: 480,
    unit: "bags",
    ingredients: "Sugar, glucose syrup, cream, butter, salt, emulsifier.",
    packaging: "300g bag. Master carton: 12 bags per case.",
    deliveryInfo: "Standard delivery: 3-5 business days.",
    featured: true,
  },
  {
    id: "7",
    name: "Oreo Original Family Pack",
    slug: "oreo-original-family-pack",
    description: "America's favourite cookie in bulk wholesale packs. Chocolate wafers with vanilla cream filling.",
    price: 26.0,
    images: [img(13), img(14)],
    category: "Cookies & Crackers",
    brand: "Oreo",
    moq: 36,
    stock: 0,
    unit: "packs",
    ingredients: "Wheat flour, sugar, vegetable oil, cocoa powder, vanilla flavouring.",
    packaging: "396g pack. Master carton: 12 packs per case.",
    deliveryInfo: "Currently out of stock. Expected restock: 2 weeks.",
  },
  {
    id: "8",
    name: "Crispy Cream Wafer Rolls",
    slug: "crispy-cream-wafer-rolls",
    description: "Delicate rolled wafers filled with rich vanilla cream. Light, crispy texture perfect for tea time.",
    price: 22.0,
    images: [img(15), img(16)],
    category: "Cream Wafers",
    brand: "SweetRoll",
    moq: 48,
    stock: 320,
    unit: "packs",
    ingredients: "Wheat flour, sugar, palm oil, cream powder, vanilla, lecithin.",
    packaging: "200g pack. Master carton: 24 packs per case.",
    deliveryInfo: "Standard delivery: 3-5 business days.",
  },
  {
    id: "9",
    name: "Hilal Freshup Bubble Gum",
    slug: "hilal-freshup-bubble-gum",
    description: "Pakistan's favourite bubble gum in assorted fruit flavours. Best-selling confectionery for retail shops.",
    price: 18.0,
    comparePrice: 22.0,
    images: [img(17), img(18)],
    category: "Hard Candies",
    brand: "Hilal Foods",
    moq: 60,
    stock: 1200,
    unit: "boxes",
    ingredients: "Sugar, gum base, glucose syrup, fruit flavouring, colours.",
    packaging: "36-piece box. Master carton: 20 boxes per case.",
    deliveryInfo: "Standard delivery: 2-4 business days.",
    featured: true,
  },
  {
    id: "10",
    name: "Candyland Jelly Beans",
    slug: "candyland-jelly-beans",
    description: "Colourful jelly beans in 12 exciting flavours. Perfect for parties, gifts, and retail display jars.",
    price: 24.0,
    comparePrice: 30.0,
    images: [img(19), img(20)],
    category: "Gummy & Jellies",
    brand: "Candyland",
    moq: 36,
    stock: 800,
    unit: "bags",
    ingredients: "Sugar, glucose syrup, starch, citric acid, natural flavours, colours.",
    packaging: "250g bag. Master carton: 24 bags per case.",
    deliveryInfo: "Standard delivery: 2-4 business days.",
    featured: true,
  },
  {
    id: "11",
    name: "Bisconni Chocolate Chip Cookies",
    slug: "bisconni-chocolate-chip-cookies",
    description: "Premium chocolate chip cookies with real chocolate chunks. A household favourite across Pakistan.",
    price: 20.0,
    comparePrice: 25.0,
    images: [img(21), img(22)],
    category: "Cookies & Crackers",
    brand: "Bisconni",
    moq: 48,
    stock: 960,
    unit: "packs",
    ingredients: "Wheat flour, chocolate chips (15%), butter, sugar, eggs, vanilla.",
    packaging: "12-pack tray. Master carton: 6 trays per case.",
    deliveryInfo: "Standard delivery: 2-4 business days.",
    featured: true,
  },
  {
    id: "12",
    name: "LU Prince Chocolate Biscuits",
    slug: "lu-prince-chocolate-biscuits",
    description: "Crispy chocolate-coated biscuits loved by kids. Top-selling school snack brand in Pakistan.",
    price: 16.0,
    comparePrice: 20.0,
    images: [img(23), img(24)],
    category: "Premium Biscuits",
    brand: "LU",
    moq: 72,
    stock: 1440,
    unit: "packs",
    ingredients: "Wheat flour, sugar, cocoa powder, vegetable oil, milk powder.",
    packaging: "Half roll pack. Master carton: 24 packs per case.",
    deliveryInfo: "Standard delivery: 2-4 business days.",
    featured: true,
  },
  {
    id: "13",
    name: "Kolson Slanty Chips",
    slug: "kolson-slanty-chips",
    description: "Crunchy slanted chips in masala and salted flavours. Pakistan's iconic snack brand.",
    price: 15.0,
    comparePrice: 18.0,
    images: [img(25), img(26)],
    category: "Cookies & Crackers",
    brand: "Kolson",
    moq: 48,
    stock: 720,
    unit: "packs",
    ingredients: "Corn, vegetable oil, salt, spices, flavour enhancers.",
    packaging: "30g pack. Master carton: 48 packs per case.",
    deliveryInfo: "Standard delivery: 2-4 business days.",
    featured: true,
  },
  {
    id: "14",
    name: "Peek Freans Sooper Biscuits",
    slug: "peek-freans-sooper-biscuits",
    description: "Classic egg & milk biscuits enriched with goodness. Pakistan's most loved tea-time companion.",
    price: 14.0,
    comparePrice: 17.0,
    images: [img(27), img(28)],
    category: "Premium Biscuits",
    brand: "Peek Freans",
    moq: 60,
    stock: 1500,
    unit: "packs",
    ingredients: "Wheat flour, sugar, eggs, milk powder, vegetable oil, leavening agents.",
    packaging: "Half roll pack. Master carton: 24 packs per case.",
    deliveryInfo: "Standard delivery: 2-4 business days.",
    featured: true,
  },
  {
    id: "15",
    name: "Cocomo Chocolate Filled Biscuits",
    slug: "cocomo-chocolate-filled-biscuits",
    description: "Fun-shaped biscuits with chocolate cream filling. Kids' all-time favourite snack brand.",
    price: 19.0,
    comparePrice: 24.0,
    images: [img(29), img(30)],
    category: "Premium Biscuits",
    brand: "Bisconni",
    moq: 48,
    stock: 640,
    unit: "packs",
    ingredients: "Wheat flour, sugar, cocoa powder, chocolate filling (18%), vegetable oil.",
    packaging: "24-piece pack. Master carton: 12 packs per case.",
    deliveryInfo: "Standard delivery: 2-4 business days.",
    featured: true,
  },
  {
    id: "16",
    name: "Mitchell's Fruit Jam Assorted",
    slug: "mitchells-fruit-jam-assorted",
    description: "Mixed fruit jam made from real fruits. A breakfast staple in every Pakistani household.",
    price: 32.0,
    comparePrice: 38.0,
    images: [img(31), img(32)],
    category: "Cookies & Crackers",
    brand: "Mitchell's",
    moq: 24,
    stock: 480,
    unit: "jars",
    ingredients: "Fruit pulp (40%), sugar, pectin, citric acid, preservative.",
    packaging: "450g jar. Master carton: 12 jars per case.",
    deliveryInfo: "Standard delivery: 3-5 business days.",
    featured: true,
  },
  {
    id: "17",
    name: "Gala Bakery Cake Rusk",
    slug: "gala-bakery-cake-rusk",
    description: "Crispy oven-baked cake rusks. Perfect with chai, a beloved desi tradition.",
    price: 12.0,
    images: [img(33), img(34)],
    category: "Premium Biscuits",
    brand: "Gala",
    moq: 48,
    stock: 960,
    unit: "packs",
    ingredients: "Wheat flour, sugar, eggs, vegetable oil, baking powder, cardamom.",
    packaging: "350g pack. Master carton: 12 packs per case.",
    deliveryInfo: "Standard delivery: 2-4 business days.",
  },
  {
    id: "18",
    name: "TUC Salted Crackers",
    slug: "tuc-salted-crackers",
    description: "Golden baked crackers with a perfect salty crunch. Great for snacking and dipping.",
    price: 17.0,
    comparePrice: 21.0,
    images: [img(35), img(36)],
    category: "Cookies & Crackers",
    brand: "LU",
    moq: 36,
    stock: 540,
    unit: "packs",
    ingredients: "Wheat flour, vegetable oil, salt, yeast, malt extract.",
    packaging: "84g pack. Master carton: 36 packs per case.",
    deliveryInfo: "Standard delivery: 2-4 business days.",
    featured: true,
  },
  {
    id: "19",
    name: "Rio Cream Wafers Vanilla",
    slug: "rio-cream-wafers-vanilla",
    description: "Crispy multi-layered wafers with smooth vanilla cream. A classic wafer loved by all ages.",
    price: 13.0,
    comparePrice: 16.0,
    images: [img(38), img(39)],
    category: "Cream Wafers",
    brand: "Continental Biscuits",
    moq: 60,
    stock: 1200,
    unit: "packs",
    ingredients: "Wheat flour, sugar, vegetable oil, cream powder, vanilla, lecithin.",
    packaging: "Half pack. Master carton: 24 packs per case.",
    deliveryInfo: "Standard delivery: 2-4 business days.",
    featured: true,
  },
  {
    id: "20",
    name: "Kim's Party Mix Snacks",
    slug: "kims-party-mix-snacks",
    description: "Assorted chips and puffs party mix. Perfect for events, parties, and everyday munching.",
    price: 25.0,
    comparePrice: 30.0,
    images: [img(40), img(41)],
    category: "Cookies & Crackers",
    brand: "Kim's",
    moq: 36,
    stock: 540,
    unit: "bags",
    ingredients: "Corn, potato starch, vegetable oil, salt, spices, flavourings.",
    packaging: "200g bag. Master carton: 18 bags per case.",
    deliveryInfo: "Standard delivery: 2-4 business days.",
    featured: true,
  },
];

export const brands = ["Royal Danish", "Belcolade", "Nestle Japan", "Haribo", "Lotus", "Werther's", "Oreo", "SweetRoll", "Hilal Foods", "Candyland", "Bisconni", "LU", "Kolson", "Peek Freans", "Mitchell's", "Gala", "Kim's", "Continental Biscuits"];
